### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by sunt05** [LllC-mmd/SHAFTS#1]

**Comment by sunt05** [comment]
@LllC-mmd I see the name "SHAFT" – which is great – in the `setup.py` file, so we'll go with it?
Can you elaborate what does this acronym represent?


then we can also rename this repo and more widely use it.

**Comment by LllC-mmd** [comment]
SHAFT, **S**imultaneous building **H**eight **A**nd **F**ootprin**T** extraction from Sentinel Imagery
