### ISSUE TITLE
cannot import name 'import_string' from 'werkzeug' when trying to download imageries

### ISSUE THREAD

**Issue by rochanofa** [LllC-mmd/SHAFTS#8]
there is an error with werkzeug when trying to download the imageries. I am running shaft on Python 3.9 on WSL (Ubuntu for Windows).
I installed the dependencies through conda.
Here's the screenshot of the error:
![image](https://user-images.githubusercontent.com/60449709/178147372-e3042b95-b8f0-49e6-96b0-0bf479d6129a.png)

**Comment by LllC-mmd** [comment]
Thanks for your interest in SHAFTS.
We have tested the deployment of SHAFTS on WSL (Ubuntu 18.04 for Windows) with Python 3.9 from Anaconda and no error related to GEE image downloading has been reported. 

![ex](https://user-images.githubusercontent.com/24932535/180628575-d7218059-6e2f-4919-9358-d3d6d8cab8fd.PNG)

And our conda environment can be listed as follows

![env](https://user-images.githubusercontent.com/24932535/180628347-583bf8e3-f547-4c16-a3e2-4297afeee9ce.png)

If you don't install SHAFTS by conda, we recommend you do so.

We also have searched for possible causes of the mentioned problem and found it may be related to other packages such as [flask](https://github.com/thadeusb/flask-cache/issues/205).

**Comment by sunt05** [comment]
Thanks @LllC-mmd for looking into the issue.

It would be good to [export](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-the-environment-yml-file) the `py39` env as `yml` file (e.g. `env.yml`) so others can set it up using 
```
conda env create -f env.yml
```

**Comment by sunt05** [comment]
This issue should now be resolved.

@rochanofa, please reopen this if any further questions arise.
